### PR TITLE
Add methods ChangeDurationFlat, ChangeDurationScale to modify animation duration

### PR DESCRIPTION
**Pull request by burnsba**
I needed a way to adjust the framerate/duration of an animated gif and ended up with these two methods. Both methods iterate over the KeyFrames, and change the KeyTimes for each frame. The total duration of the animation is adjusted to match. `ChangeDurationFlat` assumes that every KeyTime shares the same length. `ChangeDurationScale` will scale each KeyTime by a scalar factor (derived from old and new durations). Depending on the parameters and how much this gets called, this can cause KeyTimes to drift such that they no longer last the same percent time of the complete animation as they did before. The error is small, but can accumulate over time.

Both methods assume KeyTime is calculated by TimeSpan.

Changing the animation duration requires that the  `AnimationClock` associated with the animation to be recreated. I'm not sure what problems might come up from `_clock` and `_clockController` references changing, but it seems to work for my use case.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Hi @burnsba, thanks for the PR!

> `ChangeDurationFlat` assumes that every KeyTime shares the same length.

They don't, in general. The duration of each keyframe comes from the GIF itself. Some GIFs will have the same duration for each frame, but it's not always a safe assumption unless you know in advance which GIFs you will display. And anyway, the `ChangeDurationScale` would work just as well for GIFs that have the same duration for each frame, so I don't think `ChangeDurationFlat` is useful.

> `ChangeDurationScale` will scale each KeyTime by a scalar factor (derived from old and new durations).

This scenario makes more sense, I think. But couldn't this be controlled by an attached property in `ImageController` instead? The current approach is only useful if you need to change the animation speed dynamically. Is this the case in your scenario?

> Depending on the parameters and how much this gets called, this can cause KeyTimes to drift such that they no longer last the same percent time of the complete animation as they did before. The error is small, but can accumulate over time.

You could minimize the rounding errors by not converting to/from milliseconds. `TimeSpan` supports the `/` and `*` operators, so you could just do `var scaleFactor = newDuration / _animation.Duration.TimeSpan` and `keyFrame.KeyTime *= scaleFactor`. If nothing else, it makes the code simpler ;)

> 
> Both methods assume KeyTime is calculated by TimeSpan.

It is

> Changing the animation duration requires that the `AnimationClock` associated with the animation to be recreated. I'm not sure what problems might come up from `_clock` and `_clockController` references changing, but it seems to work for my use case.

There's actually a deeper problem. The animations are cached, so that if you display the same GIF multiple times, it doesn't recreate the animation. So changing the animation speed in one `ImageAnimationController` actually affects all the images that use the same animation... Ideally, the animation would have to be cloned before it's modified

Also, there's a much simpler approach to change the animation speed: the [`SpeedRatio` property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.animation.timeline.speedratio). In addition to being simpler, it doesn't have the rounding error problem discussed above (or at least, the rounding errors don't accumulate).

The ability to change the animation speed would be a useful addition to the library, but I need to think a bit more about the right approach. Could you tell me more about your use case?

**Comment by burnsba** [comment]
I'm working on a heart rate sensor visualization. My app receives heart rate information over bluetooth. There's an animated gif of a heart beat in the application; I want the gif heart rate to match the sensor heart rate. Periodically (~10 seconds) I adjust the heart beat gif to match the heart rate from the bluetooth sensor. 

I spent some time trying to get the SpeedRatio property to work but couldn't get it to change anything (before modifying WpfAnimatedGif code.) Perhaps I'm not familiar enough with WPF to know how to get it to work but I couldn't figure it out.

**Comment by thomaslevesque** [comment]
Hi @burnsba,

Thanks for the details. To be honest, I don't think this specific scenario is a very good fit for WpfAnimatedGif. You'd probably be better off using a simple animation with keyframes, as it would give you more control.

That being said, I still think this feature would be useful in WpfAnimatedGif, but probably not in the form you propose. My approach would be to add a `SpeedRatio` attached property on `ImageBehavior`, which would control the speed of the actual animation. Since the user might want to set the total duration to a specific value, without knowing the "natural" duration of the GIF animation, maybe also add a `Duration` property that would calculate the appropriate ratio (only one of the two properties could be set)

**Comment by thomaslevesque** [comment]
Hi @burnsba,

I just implemented this as described in my previous message (#69). You can set either `AnimationSpeedRatio` or `AnimationDuration`. The demo project has been updated to use this feature.

**Comment by thomaslevesque** [comment]
You can test the feature in version 2.0.0-beta.2

**Comment by burnsba** [comment]
hi @thomaslevesque , thanks for adding the feature

**Pull request closed without merging**
